version: '3.1'
services:
  app1:
    image: "app_v3:latest"
    ports:
      - "80"
    networks:
      - backend
  app2:
    image: "app_v3:latest"
    ports:
      - "80"
    networks:
      - backend
  nginx:
    image: "nginx:latest"
    ports: 
      - "127.0.0.1:80:80"
    volumes:
      - ./lbl/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
    networks:
      - backend
  db:
    image: "percona:8"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_ONETIME_PASSWORD: "true"
      MYSQL_DATABASE: example_db
    networks:
      - backend

networks:
  backend:
    driver: "bridge"